### ISSUE TITLE
iptables should be disabled, not just stopped.

### ISSUE THREAD

**Issue by hartzell** [ismaild/vagrant-centos-oracle#4]
Your provisioning rules stop the iptables firewall.  This works as long as the virtual machine remains up, but if it is shut down and restarted then the firewall is running again and clients cannot connect to oracle.

In addition to stopping the firewall, you should disable it, with e.g.

```
chkconfig iptables off
```

Alternatively, one can open a port for Oracle and save it, e.g.

```
    - name: open Oracle port in iptables
      shell: iptables -I INPUT -p tcp --dport 1521 -j ACCEPT
    - name: save iptables config
      shell: service iptables save
```

(this simple hack will duplicate the rule each time the machine is provisioned.  fancier solutions exist but this Works For Me for the now.)

**Comment by ismaild** [comment]
@hartzell thanks for the tip. I will update the Source code. I am no longer working with CentOS however as i have moved to a new project.

**Comment by hartzell** [comment]
Sounds good.  This way it'll be here for whomever comes along next and picks it up.  I'm happy.

**Comment by hartzell** [comment]
Spring cleaning, closing
